
modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'GPL-3.0-only'
showAsResourcePack = false
mods = [
	{ modId = 'dragon_rework', version = '4.5', displayName = 'Ender Dragon Rework', description = "An up in difficulty for Minecraft's final boss.\nWith more health and more attacks, the fight finally feels like the final confrontation.", logoFile = 'assets/rcube/dragon_rework/icon.png', authors = 'MrGenie151, RCube_'},
]
issueTrackerURL = 'https://github.com/CubedNetwork/EnderDragon-Rework/issues'
