name: Bump Semver

on:
  push:
    tags:
      - "chore(release): Prepare for *"

jobs:
  bump-ver:
    name: Bump Semver
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Project Version
        shell: bash
        run: |
          echo "COMMIT=${{ github.event.workflow_run.head_commit.message }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${COMMIT:29}" >> $GITHUB_ENV

      - name: Bump Version (fabric.mod.json)
        uses: restackio/update-json-file-action@2.1
        with:
          file: fabric.mod.json
          fields: "{\"version\": \"${{ env.RELEASE_VERSION }}\"}"

      - name: Bump Version (quilt.mod.json)
        uses: restackio/update-json-file-action@2.1
        with:
          file: quilt.mod.json
          fields: "{\"quilt_loader.version\": \"${{ env.RELEASE_VERSION }}\"}"

      - name: Merge to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "v${{ env.RELEASE_VERSION }}"
          git push
