name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install cargo-hack from crates.io
        uses: baptiste0928/cargo-install@main
        with:
          crate: typos-cli
      
      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: git-cliff/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: git-cliff/CHANGELOG.md
  
  publish-release:
    name: Publish Release
    needs: generate-changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: mod-version
        uses: euberdeveloper/ga-project-version@v3.0.0
        with:
          path: 'fabric.mod.json'
  
      - name: Zip Jar
        run: mkdir zip | zip -r "zip/Ender Dragon Rework-v${{ steps.mod-version.outputs.version }}.jar" ./ -x ".git/*" ".github/*"  "git-cliff/*" ".git/*" "zip/*" "README.md"

      - name: Publish to GitHub
        if: ${{ !contains(github.ref, '-') }}
        uses: "softprops/action-gh-release@v2.0.5"
        with:
          name: "Ender Dragon Rework v${{ steps.mod-version.outputs.version }}"
          tag_name: "v${{ steps.mod-version.outputs.version }}"
          body: ${{ needs.generate-changelog.outputs.release_body }}
          prerelease: false
          files: "zip/Ender Dragon Rework.jar"

      - name: Publish to GitHub (pre-release)
        if: ${{ contains(github.ref, '-') }}
        uses: "softprops/action-gh-release@v2.0.5"
        with:
          name: "Ender Dragon Rework v${{ steps.mod-version.outputs.version }}"
          tag_name: "v${{ steps.mod-version.outputs.version }}"
          body: ${{ needs.generate-changelog.outputs.release_body }}
          prerelease: true
          files: "zip/Ender Dragon Rework.jar"