name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: git-cliff/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: git-cliff/CHANGELOG.md
  
  publish-release:
    name: Publish Release
    needs: generate-changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Project Version
        id: mod-version
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "version.properties"
          properties: "version"
  
      - name: Zip Jar
        run: mkdir zip | zip -r "zip/Ender Dragon Rework.jar" ./ -x ".git/*" ".github/*"  "git-cliff/*" ".git/*" "zip/*" "README.md" "version.properties"

      - name: Publish to GitHub
        if: ${{ !contains(github.ref, '-') }}
        uses: "softprops/action-gh-release@v2.0.5"
        with:
          name: "Ender Dragon Rework v${{ steps.mod-version.outputs.version }}"
          tag_name: "v${{ steps.mod-version.outputs.version }}"
          body: ${{ needs.generate-changelog.outputs.release_body }}
          prerelease: false
          files: "zip/Ender Dragon Rework.jar"

      - name: Publish to GitHub (pre-release)
        if: ${{ contains(github.ref, '-') }}
        uses: "softprops/action-gh-release@v2.0.5"
        with:
          name: "Ender Dragon Rework v${{ steps.mod-version.outputs.version }}"
          tag_name: "v${{ steps.mod-version.outputs.version }}"
          body: ${{ needs.generate-changelog.outputs.release_body }}
          prerelease: true
          files: "zip/Ender Dragon Rework.jar"