name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  check-commands:
    name: Check commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: mcbeet/check-commands@v1.1.1
        with:
          source: .
          minecraft: 1.21.2
          stats: true

  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: git-cliff/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: git-cliff/CHANGELOG.md
  
  publish-release:
    name: Publish Release
    needs: [check-commands, generate-changelog]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Project Version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Create JAR
        run: |
          mkdir zip
          zip -r "zip/ender_dragon_rework-v${{ env.RELEASE_VERSION }}.jar" ./ -x ".git/*" ".github/*"  "git-cliff/*" ".git/*" "zip/*" "README.md" "version.properties"
          cp "zip/ender_dragon_rework-v${{ env.RELEASE_VERSION }}.jar" "zip/ender_dragon_rework.jar"

      - name: Publish to GitHub
        if: ${{ !contains(github.ref, '-') }}
        uses: softprops/action-gh-release@v2.0.6
        with:
          name: "Ender Dragon Rework v${{ env.RELEASE_VERSION }}"
          tag_name: "v${{ env.RELEASE_VERSION }}"
          body: ${{ needs.generate-changelog.outputs.release_body }}
          prerelease: false
          files: "zip/ender_dragon_rework-v${{ env.RELEASE_VERSION }}.jar"

      - name: Publish to GitHub (pre-release)
        if: ${{ contains(github.ref, '-') }}
        uses: softprops/action-gh-release@v2.0.6
        with:
          name: "Ender Dragon Rework v${{ env.RELEASE_VERSION }}"
          tag_name: "v${{ env.RELEASE_VERSION }}"
          body: ${{ needs.generate-changelog.outputs.release_body }}
          prerelease: true
          files: "zip/ender_dragon_rework-v${{ env.RELEASE_VERSION }}.jar"
