name: Release

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: mod-version
        uses: euberdeveloper/ga-project-version@v3.0.0
        with:
          path: 'fabric.mod.json'

      - name: Zip Jar
        run: mkdir zip | zip -r "zip/Ender Dragon Rework-v${{ steps.mod-version.outputs.version }}.jar" ./ -x ".git/*" ".github/*"  "git-cliff/*" ".git/*" "zip/*" "README.md"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Ender Dragon Rework-v${{ steps.mod-version.outputs.version }}
          path: |
            *
            !.git/*
            !.github/*
            !git-cliff/*
            !.gitignore
            !zip/*
            !README.md

      - name: Generate changelog
        uses: orhun/git-cliff-action@v3.1.0
        id: git-cliff
        with:
          config: git-cliff/cliff.toml
          args: -vv --latest
          # args: -vv --latest --strip header
        env:
          OUTPUT: git-cliff/CHANGELOG.md
        
      - name: DEBUG- Print Changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Release
        uses: softprops/action-gh-release@v2.0.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Ender Dragon Rework v${{ steps.mod-version.outputs.version }}"
          tag_name: "v${{ steps.mod-version.outputs.version }}"
          body: ${{ steps.git-cliff.outputs.content }}
          # body-path: git-cliff/CHANGELOG.md
          prerelease: true
          files: "zip/Ender Dragon Rework-v${{ steps.mod-version.outputs.version }}"
      
      # - name: Release
      #   uses: marvinpinto/action-automatic-releases@latest
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Ender Dragon Rework v${{ steps.mod-version.outputs.version }}"
      #     files: zip/Ender Dragon Rework-v${{ steps.mod-version.outputs.version }}.jar
