name: Nightly builds

on:
  push

jobs:
  check-commands:
    name: Check commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: mcbeet/check-commands@v1.1.1
        with:
          source: .
          minecraft: 1.21.2
          stats: true

  upload-artifact:
    name: Upload Artifact
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip Jar
        run: mkdir zip | zip -r "zip/Ender Dragon Rework.jar" ./ -x ".git/*" ".github/*"  "git-cliff/*" ".git/*" "zip/*" "README.md" "version.properties"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Ender Dragon Rework - UNTESTED
          path: zip/Ender Dragon Rework.jar 
          # path: |
          #   *
          #   !.git/*
          #   !.github/*
          #   !git-cliff/*
          #   !.gitignore
          #   !zip/*
          #   !README.md
