name: Untested Deployment (nightly builds)

on:
  push:

jobs:
  upload-release:
    name: Upload Release
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip Jar
        run: mkdir zip | zip -r "zip/Ender Dragon Rework.jar" ./ -x ".git/*" ".github/*"  "git-cliff/*" ".git/*" "zip/*" "README.md" "version.properties"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Ender Dragon Rework - UNTESTED
          path: zip/Ender Dragon Rework.jar 
          # path: |
          #   *
          #   !.git/*
          #   !.github/*
          #   !git-cliff/*
          #   !.gitignore
          #   !zip/*
          #   !README.md